version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
  
  # node:
  #   image: node:16-alpine
  #   volumes:
  #     - ./frontend:/code/frontend
  #   command: yarn watch


volumes:
  postgres_data: